### PR TITLE
[US_ND] Add "Time to release from supervision" chart on the "Supervision to Liberty" page

### LINKED ISSUE #1659: [US_ND] Add new "Time to release from supervision" chart on the "Supervision to Liberty" page
**Is your feature request related to a problem? Please describe.**
Add the "Time to release from supervision" chart on the "Supervision to Liberty" page for US_ND.

This is a `LengthOfStay` type viz.

The column to support this chart has been added to the fixture in `supervision_to_liberty_population_snapshot_by_dimension` fixture is in the` jovergaag/1556-fixtures` branch unless it has already been merged to main.

enabledFilteres: the same that are enabled for the rest of the dimension charts on that page.
accessor: `length_of_stay`

[Design](https://www.figma.com/file/Mw6kSEP2jdr9i7UVEjPuCI/UP-Consolidation?node-id=3624%3A20400)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

Added "Time to release from supervision" chart on the "Supervision to Liberty" page and fixed `time_period` values in `supervision_to_liberty_population_snapshot_by_dimension` fixture.

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1659 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by jovergaag — COMMENTED** [review]
This all looks good! I'm waiting for sign-off from Product and from Data Quality before approving.

**Comment by jovergaag** [comment]
OK It is time to pick this up again!

There is a requirements change after design review. The denominator (cohortProportion) is should now be the sum of the `dataSeries.count` instead of the `totalCount`.

Once you make that change and rebase, I will review it again!

**Comment by nasaownsky** [comment]
> OK It is time to pick this up again!
> 
> There is a requirements change after design review. The denominator (cohortProportion) is should now be the sum of the `dataSeries.count` instead of the `totalCount`.
> 
> Once you make that change and rebase, I will review it again! @nasaownsky

This makes no sense since we will always get 100% cause the sum of the `dataSeries.count` is `accumulatedCount` and we will get something like: `cohortProportion: (accumulatedCount * 100) / accumulatedCount`. Maybe we should use `d.count` in numerator: `cohortProportion: (d.count * 100) / accumulatedCount`?

**Comment by jovergaag** [comment]
> This makes no sense since we will always get 100% cause the sum of the `dataSeries.count` is `accumulatedCount` and we will get something like: `cohortProportion: (accumulatedCount * 100) / accumulatedCount`. Maybe we should use `d.count` in numerator: `cohortProportion: (d.count * 100) / accumulatedCount`?

I think you're right in that we will always get 100% on the RH side of the chart, which is what we want. I'm suggesting that we sum the count for the denominator first, then while we are iterating over dataSeries again and accumulating the count the percentage slowly increases to 100%, which is what we want. Make sense?

**Comment by jovergaag** [comment]
Closing for larger redesign work in #1720

**Pull request closed without merging**
