### PR TITLE
Multiselect redesign

### LINKED ISSUE #797: [CORE] Implement MultiSelect redesign
NOTE: All development and PRs for this task should be done against the branch `feature/core-header-refresh`.

The goal of this task is to update `MultiSelect.js` to match the design below

This is a multi-selection (checkbox) dropdown.

The dropdown should collapse when clicking outside the menu, clicking on the header item, or pressing esc.

Items should be clickable anywhere within the containing div, not just on the checkbox (i.e. you can click the label and the checkbox will fill)

Upon hover, the background should darken and the checkbox should fill in with a solid color.

If no other options are selected, "All" is automatically selected.
If "All" is selected and the user clicks on another option, "All" should become unselected.
If "All" is unselected and the user clicks on it, all other selections should clear and "All" should be the only selection.
If "All" is selected and the user clicks on it, nothing should happen.

If only one option is selected, show the name of the selected option at top. If multiple options are selected, show the name of the first selection and the a count of the remaining selections. NOTE: The title in the mock should be "Bottineau and 2 more" given the rules outlined here.

Mocks: https://www.figma.com/file/H08AQJSaAIRxfeMP4iCUPh/UP-MVP?node-id=1521%3A43

**pill**
border: 1px solid #D2D8D8;
height: 2.5rem

**item text**
weight: 500
size: 0.8rem
text-color: #00413E

**label text**
weight: 500
size: 0.8rem
text-color: #58706F

**checkbox:**
border-radius 0.25rem;
width: 1rem;
height: 1rem;
border: 1px solid #D2D8D8;

**on hover**
background: #E3E6E6
checkbox background: rgba(0, 108, 103, 0.2);
checkbox border: none;

### PR DESCRIPTION
**Pull request by AlexK-ino**
## Description of the change

changed the styles of the multi-select
updated react-select library to version 4.1.0 for compatibility with the custom scroll element
in styles weighting of selectors is increased by mentioning the tag

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #797

### Development

These boxes should be checked by the submitter prior to merging:

- [X] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by AlexK-ino** [comment]
Hi @Catacola!
I hope I'm not too late.

At the moment, selecting an item within a multi-select can change the width of the parent item, but this will be removed when all changes are merged together

**Review by Catacola — CHANGES_REQUESTED** [review]
Hi @AlexK-ino! You're not late at all. :)

This is looking really slick. I have a few pieces of feedback.

First, we should break these changesa out into a new component so we don't modify the Lantern views:
Screen Shot 2021-03-03 at 1 38 58 AM

You can call the new component CoreMultSelect.js.

Second, there seems to be a slight misalignment between the dropdown and the button. The dropdown is a few pixels wider than the button:
Screen Shot 2021-03-03 at 1 43 35 AM

If the alignment is going to be fixed by merging everything, this is looking good!

**Comment by Catacola** [comment]
Looks good! I'll manage the merges tomorrow when I have time to deal with any conflicts that come up.

**Review by Catacola — APPROVED** [review]
Looking good. Merging into feature branch.

**Pull request merged**
