### PR TITLE
[Practices] convert state codes to uppercase in auth token

### PR DESCRIPTION
**Pull request by macfarlandian**
## Description of the change

Auth0 sends us lowercase state codes in its app_metadata. For consistency with the rest of the application, this coerces those codes to uppercase before building a Firebase auth token with them. Firestore rules now expect all state codes to be uppercase. 

Verified in tests and offline mode.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)

## Related issues

n/a

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by ohaibbq** [comment]
Do we want to update the fixture data in `PracticesStore.hydrate()` as well?

**Comment by macfarlandian** [comment]
ready for another review, I have rolled back my previous changes and instead converted everything to uppercase.

**Review by Catacola — APPROVED** [review]
Just to be 100% certain, we will need to redeploy the rules when we deploy this FE since we currently have a modified version that look for lowercase tn, right?

**Comment by macfarlandian** [comment]
there's currently a modified version in place that accepts both cases ... so we should deploy this next time we update the FE but it won't immediately break anything if we don't

**Pull request merged**
