### PR TITLE
Final polish on the core header rework

### LINKED ISSUE #793: [Core] Implement new core navigation design
**Is your feature request related to a problem? Please describe.**
We need to overhaul the design of the current leadership tools. This will allow us to prep design elements for upcoming UP surfaces as well as bring this existing surface up to design standards.

**Describe the solution you'd like**
The ultimate design is documented in https://github.com/Recidiviz/pulse-dashboard/issues/777. Inidividual tasks are linked to this epic with granular details.

### PR DESCRIPTION
**Pull request by Catacola**
## Description of the change

- Fix footer color.
- Update responsive design to have a max view width
- Place the methodology view behind a feature flag
- Make sure footer doesn't jump up into view while loading.
- Move all goals into a top-level view called `\goals` and hide the tab selector on the right for now
- CSS tweaks to get IE11 to be usable
- Wrap filters when the page gets narrow
- Align dropdown items in filter menu with top item

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## PRs

Part of #897. Still need to do chart restyling
Closes #793 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by daschi — COMMENTED** [review]
The dashboard looks great on chrome, but it needs some help on IE11 on all the views. Are we merging this work in to get it into master and deployed on production? Asking because I don't know if we want to fix the styling on IE11 with this PR, or make it a separate workstream?

Screen Shot 2021-03-16 at 10 57 30 AM

**Comment by Catacola** [comment]
Oh, what did I do? It looked so much better last time I checked a commit or two ago. 😢

**Comment by Catacola** [comment]
@daschi I believe I've fixed the major issues in IE11. The profile icon is still off-center, but I think it will take more than a few css tweaks to fix that one.

**Review by daschi — APPROVED** [review]
🌷

**Pull request merged**
