### PR TITLE
[US_TN, US_ME] Add Supervision page

### LINKED ISSUE #1508: Enable the "Supervision" page for US_TN and US_ME
**Is your feature request related to a problem? Please describe.**
Enable the "Supervision" page for US_TN and US_ME. The charts that will be enabled for both of these states are "Supervision population over time", "Supervision population by district", "Supervision population by supervision level"

The filters that are enabled for both tenants for each of these charts are TIME_PERIOD, DISTRICT, and SUPERVISION_LEVEL (TIME_PERIOD is only enabled on the over time chart)

We will need to create a new metric called `supervisionPopulationOverTime` - do not use the existing `projectedSupervisionPopulationOverTime` because we do not have the projection data for these states.

The fixture files that will be used are: `supervision_population_time_series` and `supervision_population_snapshot_by_dimension`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

Enabled the "Supervision" page for US_TN and US_ME

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1508 

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by jovergaag — CHANGES_REQUESTED** [review]
Just some small changes! This looks amazing and came together so fast, thank you!

Also, Happy New Year!! We should start changing the copyright header to 2022 on all the files we touch.

**Comment by nasaownsky** [comment]
@jovergaag I'm back in the bizz! It should be ready for merge now.

**Comment by jovergaag** [comment]
> @jovergaag I'm back in the bizz! It should be ready for merge now.

Welcome back! I hope you had a restful and enjoyable vacation :)

**Review by jovergaag — APPROVED** [review]
Beautiful

**Pull request merged**
