### PR TITLE
Pathways design polish

### LINKED ISSUE #1545: Pathways design polish
**What needs to be done? Why does it need to be done?**
- [x] The LH nav has become narrower over time, it is more narrow now than figma (bottom UI in the screenshot)

- [x] The Count/Rates toggle uses the system font instead of Libre Franklin 500

- [x] The left axis is cut off on all of the rate charts (count charts seem to be fine)

**Additional context**
Add any other context about the task here.

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

Various design fixes for Pathways view.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

Closes #1545 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by nasaownsky** [comment]
Hey @jovergaag! I am facing an issue when pulling latest changes from main: the app crashes at start with this logs:

Снимок экрана 2022-01-20 в 18 02 03

I assume that this is some problem with `useIntercom`, because everything works fine as soon as I comment it in Layout files.

**Comment by jovergaag** [comment]
> Hey @jovergaag! I am facing an issue when pulling latest changes from main: the app crashes at start with this logs:

Is the problem happening on this branch? It looks like this branch is up to date with main and I'm able to run in offline mode without seeing the crash. I do remember the crash, but these new lines in `useIntercom` should have fixed it. Is it still happening for you?

```
  const hash = isDemoMode
    ? crypto
        .createHmac("sha256", process.env.REACT_APP_INTERCOM_APP_KEY)
        .update(user.sub || "")
        .digest("hex")
    : undefined;
```

**Review by jovergaag — COMMENTED** [review]
This all looks great! Waiting on review from the designer before approving.

**Comment by nasaownsky** [comment]
Yes, it is. Maybe it is because I don't have REACT_APP_INTERCOM_APP_KEY?

**Comment by jovergaag** [comment]
> Yes, it is. Maybe it is because I don't have REACT_APP_INTERCOM_APP_KEY?

You are totally right - once I deleted that form my .env i get the same error as you. I pushed up a change to the `.env-cmdrc.example` with the key to add so you no longer see this error!

@nasaownsky

**Review by jovergaag — APPROVED** [review]

**Pull request merged**
