### PR TITLE
[Workflows] Add form pre-fill and updates helpers to client for early termination

### LINKED ISSUE #2154: [Workflows] Setup firestore integration for form automation fields for pre-fill and user updates
**Is your feature request related to a problem? Please describe.**
Setup firestore integration for form automation fields for pre-fill and user updates

**Describe the solution you'd like**
Existing setup for CR: https://github.com/Recidiviz/pulse-dashboard/blob/main/src/WorkflowsStore/Client.ts#L418-L438

**Describe alternatives you've considered**
N/A

**Additional context**
Add any other context about the feature request here.

### PR DESCRIPTION
**Pull request by daschi**
## Description of the change

This is still in progress, just want to check in that I'm understanding the flow correctly. There's some items that I'm struggling with:

- When to use `TransformedEarlyTerminationReferral` type vs `EarlyTerminationDraftData` - I think we want to use `EarlyTerminationDraftData` just for populating the form component, and then `TransformedEarlyTerminationReferral` when updating firestore
- All of the fields we'll need for the `EarlyTerminationDraftData`: I think we are missing `probationExpirationDate`, `officerName`, `sidNumber`, and `judicialDistrict`. Are these expected to be on the incoming opportunity record?

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #2154

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally
- [ ] E2E have been run for Lantern changes ([Steps in the Readme](https://github.com/Recidiviz/pulse-dashboard#running-e2e-tests))

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by ohaibbq** [comment]
This is looking good! The draft data fields are a superset of what is in the referral record. The draft data will be what we persist to `earlyTermination.referralForm.data` in Firestore.

The record fields will be whatever is finalized in the  state query Recidiviz/recidiviz-data#14424.
The rest of the fields will be created dynamically by `FormInput` components calling `setEarlyTerminationReferralDataField`. I can add them once I finalize the set of rendered form inputs.

**Comment by jovergaag** [comment]
> All of the fields we'll need for the EarlyTerminationDraftData: I think we are missing probationExpirationDate, officerName, sidNumber, and judicialDistrict. Are these expected to be on the incoming opportunity record?

I think you should go ahead and add them to the opportunity record, and just make sure that the ticket to create the views knows that we are expecting those fields. The shape of the opportunity record has probably changed a bit since the original ticket was written.

**Comment by jovergaag** [comment]
> When to use TransformedEarlyTerminationReferral type vs EarlyTerminationDraftData - I think we want to use EarlyTerminationDraftData just for populating the form component, and then TransformedEarlyTerminationReferral when updating firestore

I think thats right, but I was also a little confused about what the EarlyTerminationDraftData is used for so will defer to someone who is more familiar for the final say.

**Comment by daschi** [comment]
> I think thats right, but I was also a little confused about what the EarlyTerminationDraftData is used for so will defer to someone who is more familiar for the final say.

I added `EarlyTerminationDraftData` here to be the fields that are pre-filled on the form and will be sent to the firestore record along with the other updates.

**Review by ohaibbq — APPROVED** [review]

**Review by ohaibbq — APPROVED** [review]

**Review by jovergaag — APPROVED** [review]

**Pull request merged**
