### PR TITLE
Add "Recommended for revocation" bar to race/gender charts for MO

### LINKED ISSUE #734: v2: Add "Recommended for revocation" bar to race and gender charts.
**What needs to be done? Why does it need to be done?**
Building upon #712 and #713, an additional bar should be added to the race and gender/sex charts for Lantern states for "Those recommended for revocation". This bar should be inserted below "Those who were revoked" but above "Supervised population"

This should be done for both the race and the gender/sex chart for all states. This task is blocked by the calc changes.

cc @terinpw 

**Additional context**
Add any other context about the task here.

### PR DESCRIPTION
**Pull request by jovergaag**
## Description of the change

Adds an additional bar to the race and gender/sex charts on the MO dashboard for "Those recommended for revocation". This bar should be inserted below "Those who were revoked" but above "Supervised population"

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #734

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by jovergaag** [comment]
Note: there are a bunch of console warnings in this PR (and in a few others). They are fixed in #850 so disregard for now.

**Review by daschi — COMMENTED** [review]
The data on the US_PA dashboard is showing a much lower number for all the denominators than what is being displayed in staging on both gender and race charts. Is this expected? Also, most of the percentages look the same except for the admitted population bar on the race chart for PA across all the demographics.

**Comment by jovergaag** [comment]
> The data on the US_PA dashboard is showing a much lower number for all the denominators than what is being displayed in staging on both gender and race charts. Is this expected? Also, most of the percentages look the same except for the admitted population bar on the race chart for PA across all the demographics.

I just took a look at this after merging in master and the numbers are lining up. I think the differences that you saw were probably due to different data in staging cache vs locally, or the riskLeveLMap bug that was fixed in the last couple of days. Take another look at let me know if you see any more issues!

**Review by daschi — APPROVED** [review]
👍

**Pull request merged**
