### PR TITLE
Upgrade auth0/auth0-spa-js package - fixes RECIDIVIZ-PULSE-DASHBOARD-A

### PR DESCRIPTION
**Pull request by jovergaag**
## Description of the change

We have seen a few exceptions in the dashboard within the last couple of days. I tracked it down to a bug in `@auth0/auth0-spa-s` package which was fixed in their [version 1.7.0 beta release](https://github.com/auth0/auth0-spa-js/pull/419/commits/609067aff64394a2c64fe1e0bc301e9a3e3275d7). This PR updates the auth0 package to version to the latest, version 1.12.1.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes [#XXXX]

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by jessex — APPROVED** [review]
Thanks for this, @jovergaag! To be sure there's no regression, have you manually tested all of the main auth flows when running outside of demo mode, i.e. through `yarn dev`?

**Comment by jovergaag** [comment]
@jessex No, not outside of demo mode. I have tested manually setting the stateCode for all groups from the `appMetadata` in `getUserStateCode` which looks good, but that's not testing the auth flow. Yesterday I tried creating a new user `jen+pa@recidiviz.org` and manually setting the `app_metadata.state_code` from Auth0 but once the user logged in that meta_data is overwritten, from what I can tel based on the email address. Is it a matter of permissions that would allow me to manually set and persist that user's state_code in Auth0?

**Comment by jessex** [comment]
@jovergaag great testing so far! To do the thing you want to do, you would also need to update the Auth0 rule in staging which sets user metadata on login. You'd update that to ensure that your particular email address did _not_ get its metadata set: this will make sure that you have exactly the metadata that you specified on your user in Auth0.

Once you've tried that out, let me know how it goes!

**Comment by jovergaag** [comment]
@jessex That worked like a charm, and all the auth flows look good. I'm slowly starting to find my way around Auth0! Thanks for the help.

**Pull request merged**
